[scope]
loop_at_startup = true
max_samples = 200
model = "ps2000"
oversample = 16
timebase = 5
trigger_delay = -15
trigger_rising = true
trigger_self = true
trigger_threshold = 500000
port = 39003
shots_processing_path = "~/Documents/source/yaqd-picotech/examples/process_module.py"
trigger_channel = "B"

[scope.channels.A]
enabled = true
coupling = "DC"
range = "2 V"

[scope.channels.B]
enabled = true
coupling = "DC"
range = "5 V"
invert = false
