[test]
port = 39003
trigger_self = true
trigger_name = "A"
loop_at_startup = true

[test.channels.A]
physical_channel = 0
# signal_start = 0
# signal_stop = 20
range = "2 V"
enabled = true
coupling = "DC"
invert = false
processing_method = "average"
use_baseline = false
baseline_start = 0
baseline_stop = 0

[test.channels.B]
physical_channel = 1
# signal_start = 0
# signal_stop = 20
range = "2 V"
enabled = true
coupling = "DC"
invert = false
processing_method = "average"
use_baseline = false
baseline_start = 0
baseline_stop = 0
