# https://traits.yaq.fyi/
# refer to toml.io

protocol = "picotech-adc-triggered"
doc = "Triggered Picotech Oscilloscope"
traits = ["is-daemon", "is-sensor", "has-measure-trigger"]
hardware = ["picotech:ps2000"]

[links]
source = "https://gitlab.com/yaq/yaqd-picotech"
bugtracker = "https://gitlab.com/yaq/yaqd-picotech/-/issues"
windows_c_libraries = "https://www.picotech.com/downloads"
linux_c_libraries = "https://www.picotech.com/downloads/linux"

[installation]
PyPI = "https://pypi.org/project/yaqd-picotech"

[[types]]
type = "enum"
name = "processing_method"
symbols = ["average", "sum", "min", "max"]
default = "average"

[[types]]
type = "enum"
name = "adc_range"
symbols = ["20 mV", "50 mV", "100 mV", "200 mV", "500 mV", "1 V", "2 V", "5 V", "10 V", "20 V"]
default = "5 V"

[[types]]
type = "enum"
name = "adc_coupling"
symbols = ["DC", "AC"]
default = "DC"

[[types]]
type = "record"
name = "channel"
fields = [
	{"name"="name", "type"="string"},
	{"name"="signal_start", "type"=["null", "int"]},
	{"name"="signal_stop", "type"=["null", "int"]},
	{"name"="range", "type"="adc_range", default="5 V"},
    {"name"="enabled", "type"="boolean", "default"=true},
    {"name"="coupling", "type"="adc_coupling", "default"="DC"},
	{"name"="invert", "type"="boolean", "default"=false},
	{"name"="processing_method", "type"="processing_method", "default"="average"},
	{"name"="use_baseline", "type"="boolean", "default"=false},
	{"name"="baseline_start", "type"=["null", "int"], "default"="__null__"},
	{"name"="baseline_stop", "type"=["null", "int"], "default"="__null__"},
]

[config]

[config.make]
type = "string"
default = "picotech"

[config.model]
type = "string"
default = "ps2000"

[config.timebase]
type = "int"
default = 5
doc = "Time step between measurements is `10 ns * 2^(time_base)`."

[config.max_samples]
type = "int"
default = 200
doc = "Number of samples per trigger (per channel)."

[config.oversample]
type = "int"
default = 16
doc = """\
Average on board to increase vertical resolution. \
Int between 1 and 256. \
Reduces output readings per trigger and increases time_interval in proportion.\
"""

[config.channels]
type = "map"
values = "channel"

	[[config.channels.default]]
	name = "A"
	signal_start = 0
	signal_stop = 20
	use_baseline = false

	[[config.channels.default]]
	name = "B"
	signal_start = 0
	signal_stop = 20
	use_baseline = false

[config.trigger_name]
type = "string"
doc = "Name of the trigger channel."

[config.trigger_self_trigger]
type = "boolean"
default = false
doc = """\
Sets whether (True) or not (False) ADC is triggered by its own AWG. \
AWG generates 0-1 V square wave at 1 kHz. Connect AWG to trigger.physical_channel.\
"""

[config.trigger_threshold]
type = "int"
default = 500000
doc = "Voltage value (in uV) that triggers sampling."

[config.trigger_rising]
type = "boolean"
default = true
doc = "Trigger on rising (true) or falling (false) edge"

[config.trigger_delay]
type = "float"
default = -15
doc = """\
Delay, as a percentage of sampled data points, between \
trigger and start block (delay in [-100, 100]). \
0 means trigger event is first data point, -50 means trigger \
event is in the middle of block.\
"""

[state]

[state.nshots]
type = "int"
default = 100

[messages]

[messages.get_measured_samples]
response = "ndarray"
doc = "Get an array of shape (channel, sample, shot)."

[messages.get_measured_shots]
response = "ndarray"
doc = "Get an array of shape (channel, shot)"

[messages.get_nshots]
doc = "Get the currently planned number of shots."
response = "int"

[messages.set_nshots]
doc = "Set the number of shots to acquire."
request = [{"name"="nshots", "type"="int"}]
